In [2]:
!pip install pandas pyodbc sqlalchemy

Requirement already satisfied: pandas in .\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: pyodbc in .\anaconda3\Lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in .\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: numpy>=2.3.3 in .\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in .\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in .\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in .\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import pyodbc

server = r'localhost\SQLEXPRESS'
database = 'ChurnDB'

connection_string = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    f'SERVER={server};'
    f'DATABASE={database};'
    'Trusted_Connection=yes;'
    'TrustServerCertificate=yes;'
)

conn = pyodbc.connect(connection_string)

query = "SELECT * FROM dbo.vw_ChurnData"

df = pd.read_sql(query, conn)

conn.close()

print("Data loaded successfully!")
print("Shape:", df.shape)

df.head()

C:\Users\MADHAN\AppData\Local\Temp\ipykernel_16888\3923556520.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

Data loaded successfully!
Shape: (7043, 20)

,CustomerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.850000,29.85,No
1,5575-GNVDE,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.950001,1889.50,No
2,3668-QPYBK,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.849998,108.15,Yes
3,7795-CFOCW,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.299999,1840.75,No
4,9237-HQITU,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.699997,151.65,Yes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        7043 non-null   str
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   str
 3   Dependents        7043 non-null   str
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  Contract          7043 non-null   str
 15  PaperlessBilling  7043 non-null   str
 16  PaymentMethod     7043 non-null   str
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   float64
 19  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 1.7 MB

In [5]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 7043
Columns: 20

In [6]:
df.head()

,CustomerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.850000,29.85,No
1,5575-GNVDE,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.950001,1889.50,No
2,3668-QPYBK,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.849998,108.15,Yes
3,7795-CFOCW,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.299999,1840.75,No
4,9237-HQITU,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.699997,151.65,Yes

In [7]:
df.isnull().sum()

CustomerID          0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
(df == '').sum()

CustomerID          0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [9]:
df_clean = df.drop(columns=['CustomerID']).copy()

In [10]:
df_clean.shape

(7043, 19)

In [11]:
yes_no_columns = [
    'Partner',
    'Dependents',
    'PhoneService',
    'PaperlessBilling',
    'Churn'
]

for col in yes_no_columns:
    df_clean[col] = df_clean[col].map({'Yes': 1, 'No': 0})

In [12]:
df_clean[yes_no_columns].head()

   Partner  Dependents  PhoneService  PaperlessBilling  Churn
0        1           0             0                 1      0
1        0           0             1                 0      0
2        0           0             1                 1      1
3        0           0             0                 0      0
4        0           0             1                 1      1

In [13]:
categorical_columns = [
    'MultipleLines',
    'InternetService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'Contract',
    'PaymentMethod'
]

df_clean = pd.get_dummies(
    df_clean,
    columns=categorical_columns,
    drop_first=True,
    dtype=int
)

In [14]:
print(df_clean.head())

   SeniorCitizen  Partner  Dependents  tenure  PhoneService  PaperlessBilling  \
0              0        1           0       1             0                 1
1              0        0           0      34             1                 0
2              0        0           0       2             1                 1
3              0        0           0      45             0                 0
4              0        0           0       2             1                 1

   MonthlyCharges  TotalCharges  Churn  MultipleLines_No phone service  ...  \
0       29.850000         29.85      0                               1  ...
1       56.950001       1889.50      0                               0  ...
2       53.849998        108.15      1                               0  ...
3       42.299999       1840.75      0                               1  ...
4       70.699997        151.65      1                               0  ...

   TechSupport_Yes  StreamingTV_No internet service  StreamingTV_Yes  \
0                0                                0                0
1                0                                0                0
2                0                                0                0
3                1                                0                0
4                0                                0                0

   StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                    0                    0
1                                    0                    0
2                                    0                    0
3                                    0                    0
4                                    0                    0

   Contract_One year  Contract_Two year  \
0                  0                  0
1                  1                  0
2                  0                  0
3                  1                  0
4                  0                  0

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1
1                                      0                               0
2                                      0                               0
3                                      0                               0
4                                      0                               1

   PaymentMethod_Mailed check
0                           0
1                           1
2                           1
3                           0
4                           0

[5 rows x 30 columns]

In [15]:
print(df_clean.shape)
df_clean.info()

(7043, 30)
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   Partner                                7043 non-null   int64
 2   Dependents                             7043 non-null   int64
 3   tenure                                 7043 non-null   int64
 4   PhoneService                           7043 non-null   int64
 5   PaperlessBilling                       7043 non-null   int64
 6   MonthlyCharges                         7043 non-null   float64
 7   TotalCharges                           7043 non-null   float64
 8   Churn                                  7043 non-null   int64
 9   MultipleLines_No phone service         7043 non-null   int64
 10  MultipleLines_Yes                      7043 non-null   int64
 11  InternetService_Fiber optic            7043 non-null   int64
 12  InternetService_No                     7043 non-null   int64
 13  OnlineSecurity_No internet service     7043 non-null   int64
 14  OnlineSecurity_Yes                     7043 non-null   int64
 15  OnlineBackup_No internet service       7043 non-null   int64
 16  OnlineBackup_Yes                       7043 non-null   int64
 17  DeviceProtection_No internet service   7043 non-null   int64
 18  DeviceProtection_Yes                   7043 non-null   int64
 19  TechSupport_No internet service        7043 non-null   int64
 20  TechSupport_Yes                        7043 non-null   int64
 21  StreamingTV_No internet service        7043 non-null   int64
 22  StreamingTV_Yes                        7043 non-null   int64
 23  StreamingMovies_No internet service    7043 non-null   int64
 24  StreamingMovies_Yes                    7043 non-null   int64
 25  Contract_One year                      7043 non-null   int64
 26  Contract_Two year                      7043 non-null   int64
 27  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 28  PaymentMethod_Electronic check         7043 non-null   int64
 29  PaymentMethod_Mailed check             7043 non-null   int64
dtypes: float64(2), int64(28)
memory usage: 1.6 MB

In [16]:
print(df_clean.isnull().sum())

SeniorCitizen                            0
Partner                                  0
Dependents                               0
tenure                                   0
PhoneService                             0
PaperlessBilling                         0
MonthlyCharges                           0
TotalCharges                             0
Churn                                    0
MultipleLines_No phone service           0
MultipleLines_Yes                        0
InternetService_Fiber optic              0
InternetService_No                       0
OnlineSecurity_No internet service       0
OnlineSecurity_Yes                       0
OnlineBackup_No internet service         0
OnlineBackup_Yes                         0
DeviceProtection_No internet service     0
DeviceProtection_Yes                     0
TechSupport_No internet service          0
TechSupport_Yes                          0
StreamingTV_No internet service          0
StreamingTV_Yes                          0
StreamingMovies_No internet service      0
StreamingMovies_Yes                      0
Contract_One year                        0
Contract_Two year                        0
PaymentMethod_Credit card (automatic)    0
PaymentMethod_Electronic check           0
PaymentMethod_Mailed check               0
dtype: int64

In [17]:
print("Total missing values:", df_clean.isnull().sum().sum())

Total missing values: 0

In [18]:
output_file = 'cleaned_churn_data.csv'

df_clean.to_csv(output_file, index=False)

print(f"Cleaned dataset saved successfully as {output_file}")

Cleaned dataset saved successfully as cleaned_churn_data.csv

In [19]:
import os

print("File exists:", os.path.exists(output_file))
print("File location:", os.path.abspath(output_file))

File exists: True
File location: C:\Users\MADHAN\cleaned_churn_data.csv

In [32]:
print(df_clean.shape)
df_clean.head()

(7043, 32)

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,MultipleLines_No phone service,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,TotalServicesUsed,AvgMonthlySpend
0,0,1,0,1,0,1,29.850000,29.85,0,1,...,0,0,0,0,0,0,1,0,2,29.850000
1,0,0,0,34,1,0,56.950001,1889.50,0,0,...,0,0,0,1,0,0,0,1,4,55.573529
2,0,0,0,2,1,1,53.849998,108.15,1,0,...,0,0,0,0,0,0,0,1,4,54.075000
3,0,0,0,45,0,0,42.299999,1840.75,0,1,...,0,0,0,1,0,0,0,0,4,40.905556
4,0,0,0,2,1,1,70.699997,151.65,1,0,...,0,0,0,0,0,0,1,0,2,75.825000

In [21]:
df_clean['TotalServicesUsed'] = (
    df_clean['PhoneService']
    + df_clean['MultipleLines_Yes']
    + (1 - df_clean['InternetService_No'])
    + df_clean['OnlineSecurity_Yes']
    + df_clean['OnlineBackup_Yes']
    + df_clean['DeviceProtection_Yes']
    + df_clean['TechSupport_Yes']
    + df_clean['StreamingTV_Yes']
    + df_clean['StreamingMovies_Yes']
)

In [22]:
df_clean[['TotalServicesUsed', 'Churn']].head(10)

   TotalServicesUsed  Churn
0                  2      0
1                  4      0
2                  4      1
3                  4      0
4                  2      1
5                  6      1
6                  5      0
7                  2      0
8                  7      1
9                  4      0

In [23]:
import numpy as np

df_clean['AvgMonthlySpend'] = np.where(
    df_clean['tenure'] > 0,
    df_clean['TotalCharges'] / df_clean['tenure'],
    df_clean['MonthlyCharges']
)

In [24]:
df_clean[['tenure', 'TotalCharges', 'MonthlyCharges', 'AvgMonthlySpend']].head(10)

   tenure  TotalCharges  MonthlyCharges  AvgMonthlySpend
0       1         29.85       29.850000        29.850000
1      34       1889.50       56.950001        55.573529
2       2        108.15       53.849998        54.075000
3      45       1840.75       42.299999        40.905556
4       2        151.65       70.699997        75.825000
5       8        820.50       99.650002       102.562500
6      22       1949.40       89.099998        88.609091
7      10        301.90       29.750000        30.190000
8      28       3046.05      104.800003       108.787500
9      62       3487.95       56.150002        56.257258

In [25]:
print(df_clean[['TotalServicesUsed', 'AvgMonthlySpend']].describe())

       TotalServicesUsed  AvgMonthlySpend
count        7043.000000      7043.000000
mean            4.146244        64.762906
std             2.312720        30.189796
min             1.000000        13.775000
25%             2.000000        35.935156
50%             4.000000        70.337500
75%             6.000000        90.174158
max             9.000000       121.400000

In [26]:
print(
    df_clean[['TotalServicesUsed', 'AvgMonthlySpend']].isnull().sum()
)

TotalServicesUsed    0
AvgMonthlySpend      0
dtype: int64

In [27]:
correlation = df_clean[
    ['TotalServicesUsed', 'AvgMonthlySpend', 'Churn']
].corr()

print(correlation)

                   TotalServicesUsed  AvgMonthlySpend     Churn
TotalServicesUsed           1.000000         0.849024 -0.019375
AvgMonthlySpend             0.849024         1.000000  0.192531
Churn                      -0.019375         0.192531  1.000000

In [28]:
print("TotalServicesUsed vs Churn:",
      df_clean['TotalServicesUsed'].corr(df_clean['Churn']))

print("AvgMonthlySpend vs Churn:",
      df_clean['AvgMonthlySpend'].corr(df_clean['Churn']))

TotalServicesUsed vs Churn: -0.01937481319464759
AvgMonthlySpend vs Churn: 0.19253058324160813

In [29]:
print("Shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum().sum())

print("\nData types:")
print(df_clean.dtypes)

Shape: (7043, 32)

Missing values:
0

Data types:
SeniorCitizen                              int64
Partner                                    int64
Dependents                                 int64
tenure                                     int64
PhoneService                               int64
PaperlessBilling                           int64
MonthlyCharges                           float64
TotalCharges                             float64
Churn                                      int64
MultipleLines_No phone service             int64
MultipleLines_Yes                          int64
InternetService_Fiber optic                int64
InternetService_No                         int64
OnlineSecurity_No internet service         int64
OnlineSecurity_Yes                         int64
OnlineBackup_No internet service           int64
OnlineBackup_Yes                           int64
DeviceProtection_No internet service       int64
DeviceProtection_Yes                       int64
TechSupport_No internet service            int64
TechSupport_Yes                            int64
StreamingTV_No internet service            int64
StreamingTV_Yes                            int64
StreamingMovies_No internet service        int64
StreamingMovies_Yes                        int64
Contract_One year                          int64
Contract_Two year                          int64
PaymentMethod_Credit card (automatic)      int64
PaymentMethod_Electronic check             int64
PaymentMethod_Mailed check                 int64
TotalServicesUsed                          int64
AvgMonthlySpend                          float64
dtype: object

In [30]:
output_file = 'engineered_churn_data.csv'

df_clean.to_csv(output_file, index=False)

print("Engineered dataset saved successfully!")
print("File:", output_file)

Engineered dataset saved successfully!
File: engineered_churn_data.csv

In [31]:
import os

print("File exists:", os.path.exists(output_file))
print("Location:", os.path.abspath(output_file))

File exists: True
Location: C:\Users\MADHAN\engineered_churn_data.csv